lms/contas/urls.py
from django.urls import path
from contas import views

app_name = 'contas'

urlpatterns = [
    path('lista-alunos/', views.listar_alunos, name='lista-alunos'),
    path('cadastrar-aluno/', views.cadastrar_alunos, name='cadastrar-aluno'),
    path('altera-aluno/<int:aluno_id>/', views.alterar_aluno, name='altera-aluno'),
    path('excluir-aluno/<int:aluno_id>/', views.excluir_aluno, name='excluir-aluno'),
    path('lista-coordenadores/', views.listar_coordenadores, name='lista-coordenadores'),
    path('cadastrar-coordenador/', views.cadastrar_coordenador, name='cadastrar-coordenador'),
    path('altera-coordenador/<int:coordenador_id>/', views.alterar_coordenador, name='altera-coordenador'),
    path('excluir-coordenador/<int:coordenador_id>/', views.excluir_coordenador, name='excluir-coordenador'),
    path('lista-professores/', views.listar_professores, name='lista-professores'),
    path('cadastrar-professor/', views.cadastrar_professor, name='cadastrar-professor'),
    path('altera-professor/<int:professor_id>/', views.alterar_professor, name='altera-professor'),
    path('excluir-professor/<int:professor_id>/', views.excluir_professor, name='excluir-professor'),
    path('lista-mensagens/', views.listar_mensagens, name='lista-mensagens'),
    path('cadastrar-mensagem/', views.cadastrar_mensagem, name='cadastrar-mensagem'),
    path('altera-mensagem/<int:mensagem_id>/', views.alterar_mensagem, name='altera-mensagem'),
    path('excluir-mensagem/<int:mensagem_id>/', views.excluir_mensagem, name='excluir-mensagem')
]

lms/core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index')
]

lms/curriculo/urls.py
from django.urls import path
from curriculo import views

app_name = 'curriculo'

urlpatterns = [
    path('lista-cursos/', views.listar_cursos, name='lista-cursos'),
    path('cadastrar-curso/', views.cadastrar_curso, name='cadastrar-curso'),
    path('altera-curso/<int:curso_id>/', views.alterar_curso, name='altera-curso'),
    path('excluir-curso/<int:curso_id>/', views.excluir_curso, name='excluir-curso'),

    path('lista-disciplinas/', views.listar_disciplinas, name='lista-disciplinas'),
    path('cadastrar-disciplina/', views.cadastrar_disciplina, name='cadastrar-disciplina'),
    path('altera-disciplina/<int:disciplina_id>/', views.alterar_disciplina, name='altera-disciplina'),
    path('excluir-disciplina/<int:disciplina_id>/', views.excluir_disciplina, name='excluir-disciplina'),

    path('lista-disciplinas-ofertadas/', views.listar_disciplinas_ofertadas, name='lista-disciplinas-ofertadas'),
    path('cadastrar-disciplina-ofertada/', views.cadastrar_disciplina_ofertada, name='cadastrar-disciplina-ofertada'),
    path('altera-disciplina-ofertada/<int:id>/', views.alterar_disciplina_ofertada, name='altera-disciplina-ofertada'),
    path('excluir-disciplina-ofertada/<int:id>/', views.excluir_disciplina_ofertada, name='excluir-disciplina-ofertada')
]

lms/lms/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

lms/restrito/urls.py
from django.urls import path
from restrito import views

app_name = 'restrito'

urlpatterns = [
    path('lista-atividades', views.listar_atividades, name='lista-atividades'),
    path('cadastrar-atividade', views.cadastrar_atividade, name='cadastrar-atividade'),
    path('alterar-atividade/<int:atividade_id>', views.alterar_atividade, name='alterar-atividade'),
    path('excluir-atividade/<int:atividade_id>', views.excluir_atividade, name='excluir-atividade')
]

lms/core/models.py
from django.db import models

# Create your models here.

lms/core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

lms/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static "css/normalize.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>LMS - Home</title>
</head>
<body>

    <nav>
        <ul class="menu">
            <li>&nbsp;&nbsp;&nbsp;</li>
            <li><a href="{% url 'core:index' %}">LMS</a></li>
            <li><a href="{% url 'contas:lista-alunos' %}">Aluno</a></li>
            <li><a href="{% url 'contas:lista-coordenadores' %}">Coordenador</a></li>
            <li><a href="{% url 'contas:lista-professores' %}">Professor</a></li>
            <li><a href="{% url 'contas:lista-mensagens' %}">Mensagem</a></li>
            <li><a href="{% url 'curriculo:lista-cursos' %}">Curso</a></li>
            <li><a href="{% url 'curriculo:lista-disciplinas' %}">Disciplina</a></li>
            <li><a href="{% url 'curriculo:lista-disciplinas-ofertadas' %}">Disciplinas Ofertadas</a></li>
            <li><a href="{% url 'restrito:lista-atividades' %}">Atividades</a></li>
            <li class="right"><a href="login.html" target="_blank">Login</a></li>
            <li class="right">&nbsp;</li>
        </ul>
    </nav>

    <div class="conteudo">
        {% block body %}
        {% endblock %}
    </div>

    <footer>
        <div>
            <div class="linha">
                <div class="col-md-4">
                    <h1>LMS</h1>
                    <p class="sociais">Siga a gente nas redes sociais</p>
                    <img src="{% static 'img/facebook.png' %}" alt="Facebook">
                    <img src="{% static 'img/twitter.png' %}" alt="Twitter">
                    <img src="{% static 'img/linkedin.png' %}" alt="Linkedin">
                    <img src="{% static 'img/instagram.png' %}" alt="Instagram">
                    <p>Todos os direitos reservados.</p>
                </div>
                <div class="col-md-4">
                    <h2>Contato</h2>
                    <p><strong>Telefone</strong></p>
                    <p>(11) 4141-4141</p>
                    <p><strong>Endereço</strong></p>
                    <p>Rua X, 44 - Bairro Y - Cidade Z / SP </p>
                </div>
                <div class="col-md-4">
                    <h2>Atendimento</h2>
                    <p>De Segunda a Sexta - Das 8h ás 22h</p>
                </div>

            </div>
        </div>
    </footer>
</body>
</html>

lms/core/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div id="premios">
            <h1 class="text-center">PRÊMIOS E RECONHECIMENTOS</h1>
            <br>
            <img src="{% static 'img/medalha.png' %}" style="margin-left: 48%" alt="Medalha">
            <div class="frase-reconhecimento">
                <p>
                    A Instituição é altamente reconhecida por sua atuação no mercado da educação,
                    o que comprova o compromisso da Instituição com o ensino de qualidade e a dedicação do
                    Grupo em transformar a sociedade através da tecnologia. Desta maneira,
                    ao longo dos anos a Faculdade tem recebido prêmios e reconhecimentos que são
                    resultados do trabalho contínuo de professores e funcionários e da determinação de seus
                    alunos.
                </p>
            </div>
            <br>
            <br>
            <div class="linha">
                <div class="col-md-4">
                    <img class="img-centro" src="{% static 'img/premios.png' %}" alt="Prêmios">
                    <br>
                    <h2>MAIOR NOTA ENADE</h2>
                </div>
                <div class="col-md-4">
                    <img class="img-centro" src="{% static 'img/premios.png' %}" alt="Prêmios">
                    <br>
                    <h2>MAIOR NOTA ENADE/MEC</h2>
                </div>
                <div class="col-md-4">
                    <img class="img-centro" src="{% static 'img/premios.png' %}" alt="Prêmios">
                    <br>
                    <h2>TOP 10 ENADE/MEC</h2>
                </div>
            </div>
        </div>

        <hr>

        <div id="noticias">
            <h1 class="text-center">Notícias</h1>
            <div class="linha">
                <div class="col-md-4">
                    <img src="{% static 'img/noticia1.png' %}" alt="Estudar" width="350" height="200px">
                    <p>Saiba como ter foco para estudar.</p>
                    <a href="#">Ver Mais</a>
                </div>
                <div class="col-md-4">
                    <img src="{% static 'img/noticia2.png' %}" alt="Estudar" width="350" height="200px">
                    <p>Saiba como ganhar dinheiro.</p>
                    <a href="#">Ver Mais</a>
                </div>
                <div class="col-md-4">
                    <img src="{% static 'img/noticia3.png' %}" alt="Estudar" width="350" height="200px">
                    <p>Saiba como ser mais produtivo.</p>
                    <a href="#">Ver Mais</a>
                </div>
            </div>
        </div>

        <hr>

        <div id="depoimentos">
            <h1 class="text-center">Depoimentos</h1>
            <div class="linha">
                <div class="col-md-4">
                    <p class="depoimento">"Faculdade muito boa, professores excelentes e comida muito boa."</p>
                    <div class="linha">
                        <div class="col-md-3"><img src="{% static 'img/user.png' %}" alt="Aluno"></div>
                        <div class="col-md-9"><p><strong>Nicolas Rezende</strong></p></div>
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="depoimento">"Infraestrutura muito boa, atendimento excelente e professores super capacitados."</p>
                    <div class="linha">
                        <div class="col-md-3"><img src="{% static 'img/user.png' %}" alt="Aluno"></div>
                        <div class="col-md-9"><p><strong>João Silva</strong></p></div>
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="depoimento">"Ensino nota 10, direção super preocupada com o ensino."</p>
                    <div class="linha">
                        <div class="col-md-3"><img src="{% static 'img/user.png' %}" alt="Aluno"></div>
                        <div class="col-md-9"><p><strong>Ana Julia</strong></p></div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}