lms/contas/urls.py
from django.urls import path
from contas import views

app_name = 'contas'

urlpatterns = [
    path('lista-alunos/', views.listar_alunos, name='lista-alunos'),
    path('cadastrar-aluno/', views.cadastrar_alunos, name='cadastrar-aluno'),
    path('altera-aluno/<int:aluno_id>/', views.alterar_aluno, name='altera-aluno'),
    path('excluir-aluno/<int:aluno_id>/', views.excluir_aluno, name='excluir-aluno'),
    path('lista-coordenadores/', views.listar_coordenadores, name='lista-coordenadores'),
    path('cadastrar-coordenador/', views.cadastrar_coordenador, name='cadastrar-coordenador'),
    path('altera-coordenador/<int:coordenador_id>/', views.alterar_coordenador, name='altera-coordenador'),
    path('excluir-coordenador/<int:coordenador_id>/', views.excluir_coordenador, name='excluir-coordenador'),
    path('lista-professores/', views.listar_professores, name='lista-professores'),
    path('cadastrar-professor/', views.cadastrar_professor, name='cadastrar-professor'),
    path('altera-professor/<int:professor_id>/', views.alterar_professor, name='altera-professor'),
    path('excluir-professor/<int:professor_id>/', views.excluir_professor, name='excluir-professor'),
    path('lista-mensagens/', views.listar_mensagens, name='lista-mensagens'),
    path('cadastrar-mensagem/', views.cadastrar_mensagem, name='cadastrar-mensagem'),
    path('altera-mensagem/<int:mensagem_id>/', views.alterar_mensagem, name='altera-mensagem'),
    path('excluir-mensagem/<int:mensagem_id>/', views.excluir_mensagem, name='excluir-mensagem')
]

lms/core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index')
]

lms/curriculo/urls.py
from django.urls import path
from curriculo import views

app_name = 'curriculo'

urlpatterns = [
    path('lista-cursos/', views.listar_cursos, name='lista-cursos'),
    path('cadastrar-curso/', views.cadastrar_curso, name='cadastrar-curso'),
    path('altera-curso/<int:curso_id>/', views.alterar_curso, name='altera-curso'),
    path('excluir-curso/<int:curso_id>/', views.excluir_curso, name='excluir-curso'),

    path('lista-disciplinas/', views.listar_disciplinas, name='lista-disciplinas'),
    path('cadastrar-disciplina/', views.cadastrar_disciplina, name='cadastrar-disciplina'),
    path('altera-disciplina/<int:disciplina_id>/', views.alterar_disciplina, name='altera-disciplina'),
    path('excluir-disciplina/<int:disciplina_id>/', views.excluir_disciplina, name='excluir-disciplina'),

    path('lista-disciplinas-ofertadas/', views.listar_disciplinas_ofertadas, name='lista-disciplinas-ofertadas'),
    path('cadastrar-disciplina-ofertada/', views.cadastrar_disciplina_ofertada, name='cadastrar-disciplina-ofertada'),
    path('altera-disciplina-ofertada/<int:id>/', views.alterar_disciplina_ofertada, name='altera-disciplina-ofertada'),
    path('excluir-disciplina-ofertada/<int:id>/', views.excluir_disciplina_ofertada, name='excluir-disciplina-ofertada')
]

lms/lms/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

lms/curriculo/models.py
from django.db import models
from contas.models import Coordenador, Professor

class Curso(models.Model):
    nome = models.CharField('Nome', db_column='NOME', unique=True, max_length=100)

class Disciplina(models.Model):
    nome = models.CharField('Nome', db_column='NOME', unique=True, max_length=30)
    data = models.DateTimeField('Data', db_column='DATA', blank=True, null=True)
    status = models.CharField('Status', db_column='STATUS', max_length=7, blank=True, null=True)
    plano_ensino = models.CharField('Plano de Ensino', db_column='PLANOENSINO', max_length=8000, blank=True, null=True)
    carga_horaria = models.SmallIntegerField('Carga Horária', db_column='CARGAHORARIA')
    competencias = models.CharField('Competencias', max_length=450, blank=True, null=True)
    habilidades = models.CharField('Habilidades', max_length=500, blank=True, null=True)
    ementa = models.CharField('Ementa', max_length=300, blank=True, null=True)
    conteudo_programatico = models.CharField('Conteúdo Programatico', db_column='CONTEUDOPROGRAMATICO', max_length=1000, blank=True, null=True)
    bibliografia_basica = models.CharField('Bibliografia Básica', max_length=700, db_column='BIBLIOGRAFIABASICA', blank=True, null=True)
    bibliografia_complementar = models.CharField('Bibliografia Complementar', max_length=700, db_column='BIBLIOGRAFIACOMPLEMENTAR', blank=True, null=True)
    percentual_pratico = models.IntegerField('Percentual Prático', db_column='PERCENTUALPRATICO', blank=True, null=True)
    percentual_teorico = models.IntegerField('Percentual Teórico', db_column='PERCENTUALTEORICO', blank=True, null=True)
    idcoordenador = models.ForeignKey(Coordenador, db_column='idcoordenador', blank=True, null=True, on_delete=True)

class Disciplinaofertada(models.Model):
    idcoordenador = models.ForeignKey(Coordenador, db_column='IdCoordenador', on_delete=True)
    dtiniciomatricula = models.DateField(blank=True, null=True)
    dtfimatricula = models.DateField(blank=True, null=True)
    iddisciplina = models.ForeignKey(Disciplina, db_column='IDDISCIPLINA', on_delete=True)
    idcurso = models.ForeignKey(Curso, db_column='IDCURSO', on_delete=True)
    ano = models.SmallIntegerField(db_column='ANO')
    semestre = models.IntegerField(db_column='SEMESTRE')
    turma = models.CharField(db_column='TURMA', max_length=1)
    idprofessor = models.ForeignKey(Professor, db_column='IDPROFESSOR', blank=True, null=True, on_delete=True)
    metodologia = models.CharField(db_column='METODOLOGIA', max_length=150, blank=True, null=True)
    recursos = models.CharField(db_column='RECURSOS', max_length=150, blank=True, null=True)
    criterio_avaliacao = models.CharField(db_column='CRITERIOAVALIACAO', max_length=60, blank=True, null=True)
    planode_aulas = models.CharField(db_column='PLANODEAULAS', max_length=500, blank=True, null=True)

lms/curriculo/views.py
from django.shortcuts import render, redirect
from curriculo.models import Curso, Disciplina, Disciplinaofertada
from contas.models import Coordenador, Professor
from datetime import datetime

def cadastrar_curso(request):
    if request.method == 'GET':
        return render(request, 'cadastro-curso.html')
    else:
        if request.POST.get('id'):
            curso = Curso(id=request.POST.get('id'), nome=request.POST.get('nome'))
        else:
            curso = Curso(nome=request.POST.get('nome'))
        curso.save()
        return redirect('/curriculo/lista-cursos')

def listar_cursos(request):
    return render(request, 'lista-cursos.html', {'cursos': Curso.objects.all()})

def alterar_curso(request, curso_id):
    curso = Curso.objects.get(id=curso_id)
    return render(request, 'cadastro-curso.html', {'curso': curso})

def excluir_curso(request, curso_id):
    curso = Curso.objects.get(id=curso_id)
    curso.delete()
    return redirect('/curriculo/lista-cursos')

def cadastrar_disciplina(request):
    if request.method == 'GET':
        return render(request, 'cadastro-disciplina.html', {'coordenadores': Coordenador.objects.all()})
    else:
        disciplina = Disciplina(nome=request.POST.get('nome'), data=datetime.today(), status=request.POST.get('status'),
                                carga_horaria=request.POST.get('cargahoraria'), percentual_pratico=0,
                                percentual_teorico=0,
                                idcoordenador=Coordenador.objects.get(id=request.POST.get('coordenador')),
                                plano_ensino=request.POST.get('ensino'), competencias=request.POST.get('competencias'),
                                habilidades=request.POST.get('habilidades'), ementa=request.POST.get('ementa'),
                                conteudo_programatico=request.POST.get('conteudo'), bibliografia_basica=request.POST.get('basica'),
                                bibliografia_complementar=request.POST.get('complementar'))
        if request.POST.get('teorico'):
            disciplina.percentual_teorico = request.POST.get('teorico')
        if request.POST.get('pratico'):
            disciplina.percentual_pratico = request.POST.get('pratico')
        if request.POST.get('id'):
            disciplina.id = request.POST.get('id')
        disciplina.save()
        return redirect('/curriculo/lista-disciplinas')

def listar_disciplinas(request):
    return render(request, 'lista-disciplinas.html', {'disciplinas': Disciplina.objects.all()})

def alterar_disciplina(request, disciplina_id):
    disciplina = Disciplina.objects.get(id=disciplina_id)
    return render(request, 'cadastro-disciplina.html', {'disciplina': disciplina, 'coordenadores': Coordenador.objects.all()})

def excluir_disciplina(request, disciplina_id):
    disciplina = Disciplina.objects.get(id=disciplina_id)
    disciplina.delete()
    return redirect('/curriculo/lista-disciplinas')

def cadastrar_disciplina_ofertada(request):
    if request.method == 'GET':
        cursos = Curso.objects.all()
        professores = Professor.objects.all()
        coordenadores = Coordenador.objects.all()
        disciplinas = Disciplina.objects.all()
        return render(request, 'cadastro-disciplina-ofertada.html', {'cursos': cursos,
                'professores': professores, 'coordenadores': coordenadores, 'disciplinas': disciplinas})
    else:        
        disciplina_ofertada = Disciplinaofertada(dtiniciomatricula=request.POST.get('datainicio'),
            dtfimatricula=request.POST.get('datafim'), ano=request.POST.get('ano'), 
            semestre=request.POST.get('semestre'), turma=request.POST.get('turma'), 
            metodologia=request.POST.get('metodologia'), recursos=request.POST.get('recursos'),
            criterio_avaliacao=request.POST.get('criterio'), planode_aulas=request.POST.get('planoaulas'),
            idprofessor=Professor.objects.get(id=request.POST.get('professor')),
            idcoordenador=Coordenador.objects.get(id=request.POST.get('coordenador')),
            idcurso = Curso.objects.get(id=request.POST.get('curso')),
            iddisciplina=Disciplina.objects.get(id=request.POST.get('disciplina')))
        if request.POST.get('id'):
            disciplina_ofertada.id = request.POST.get('id')
        disciplina_ofertada.save()
        return redirect('/curriculo/lista-disciplinas-ofertadas')

def listar_disciplinas_ofertadas(request):
    disciplinas_ofertadas = Disciplinaofertada.objects.all()
    return render(request, 'lista-disciplinas-ofertadas.html', 
        {'disciplinas_ofertadas': disciplinas_ofertadas})

def alterar_disciplina_ofertada(request, id):
    cursos = Curso.objects.all()
    professores = Professor.objects.all()
    coordenadores = Coordenador.objects.all()
    disciplinas = Disciplina.objects.all()
    disciplina_ofertada = Disciplinaofertada.objects.get(id=id)
    datainicio = str(disciplina_ofertada.dtiniciomatricula)
    datafim = str(disciplina_ofertada.dtfimatricula)
    return render(request, 'cadastro-disciplina-ofertada.html', {'disciplina_ofertada': disciplina_ofertada,
                'cursos': cursos, 'professores': professores, 'coordenadores': coordenadores, 
                'disciplinas': disciplinas, 'datainicio': datainicio, 'datafim': datafim})

def excluir_disciplina_ofertada(request, id):
    disciplina_ofertada = Disciplinaofertada.objects.get(id=id)
    disciplina_ofertada.delete()
    return redirect('/curriculo/lista-disciplinas-ofertadas')

lms/curriculo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static "css/normalize.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>LMS - Home</title>
</head>
<body>

    <nav>
        <ul class="menu">
            <li>&nbsp;&nbsp;&nbsp;</li>
            <li><a href="{% url 'core:index' %}">LMS</a></li>
            <li><a href="{% url 'contas:lista-alunos' %}">Aluno</a></li>
            <li><a href="{% url 'contas:lista-coordenadores' %}">Coordenador</a></li>
            <li><a href="{% url 'contas:lista-professores' %}">Professor</a></li>
            <li><a href="{% url 'contas:lista-mensagens' %}">Mensagem</a></li>
            <li><a href="{% url 'curriculo:lista-cursos' %}">Curso</a></li>
            <li><a href="{% url 'curriculo:lista-disciplinas' %}">Disciplina</a></li>
            <li class="right"><a href="login.html" target="_blank">Login</a></li>
            <li class="right">&nbsp;</li>
        </ul>
    </nav>

    <div class="conteudo">
        {% block body %}
        {% endblock %}
    </div>

    <footer>
        <div>
            <div class="linha">
                <div class="col-md-4">
                    <h1>LMS</h1>
                    <p class="sociais">Siga a gente nas redes sociais</p>
                    <img src="{% static 'img/facebook.png' %}" alt="Facebook">
                    <img src="{% static 'img/twitter.png' %}" alt="Twitter">
                    <img src="{% static 'img/linkedin.png' %}" alt="Linkedin">
                    <img src="{% static 'img/instagram.png' %}" alt="Instagram">
                    <p>Todos os direitos reservados.</p>
                </div>
                <div class="col-md-4">
                    <h2>Contato</h2>
                    <p><strong>Telefone</strong></p>
                    <p>(11) 4141-4141</p>
                    <p><strong>Endereço</strong></p>
                    <p>Rua X, 44 - Bairro Y - Cidade Z / SP </p>
                </div>
                <div class="col-md-4">
                    <h2>Atendimento</h2>
                    <p>De Segunda a Sexta - Das 8h ás 22h</p>
                </div>

            </div>
        </div>
    </footer>
</body>
</html>

lms/curriculo/templates/cadastro-curso.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Cadastro de Cursos</h1>
    <hr>

    <form action="{% url 'curriculo:cadastrar-curso' %}" method="post">
        <div class="linha">
            {% csrf_token %}
            <input type="number" name="id" hidden value="{{ curso.id }}">
            <div class="col-md-6">
                <div class="form-grupo">
                    <label for="nome">Nome:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" size="20"
                    size="20" name="nome" id="nome" required value="{{ curso.nome }}">
                </div>
            </div>
            <div class="form-grupo">
                <button type="submit" class="btn" style="margin-left: 50%;">Salvar Curso</button>
            </div>
        </div>
    </form>
{% endblock %}

lms/curriculo/templates/cadastro-disciplina-ofertada.html
{% extends 'base.html' %}
{% block body %}
<h1 class="text-center">Cadastro de Disciplinas Ofertadas</h1>
<hr>

<form action="{% url 'curriculo:cadastrar-disciplina-ofertada' %}" method="post">
    <div class="linha">
        {% csrf_token %}
        <input type="number" name="id" hidden value="{{ disciplina_ofertada.id }}">
        <div class="col-md-6">
            <div class="form-grupo">
                <label for="professor">Professor:</label>
                <label class="ast">*</label> <br>
                <select name="professor">
                    {% for professor in professores %}
                        <option value="{{ professor.id }}"
                                {% if professor.id == disciplina_ofertada.idprofessor.id %}selected{% endif %}>
                            {{ professor.nome }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-grupo">
                <label for="curso">Curso:</label>
                <label class="ast">*</label> <br>
                <select name="curso">
                    {% for curso in cursos %}
                        <option value="{{ curso.id }}"
                                {% if curso.id == disciplina_ofertada.idcurso.id %}selected{% endif %}>
                            {{ curso.nome }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-grupo">
                <label for="datainicio">Data Início:</label>
                <input type="date" size="20"
                size="20" name="datainicio" id="datainicio" value="{{ datainicio }}">
            </div>
            <div class="form-grupo">
                <label for="ano">Ano:</label>
                <label class="ast">*</label> <br>
                <input type="number" size="20"
                size="20" name="ano" id="ano" value="{{ disciplina_ofertada.ano }}">
            </div>
            <div class="form-grupo">
                <label for="turma">Turma:</label>
                <label class="ast">*</label> <br>
                <input type="text" size="20"
                size="20" name="turma" id="turma" value="{{ disciplina_ofertada.turma }}">
            </div>
            <div class="form-grupo">
                <label for="metodologia">Metodologia:</label>
                <input type="text" size="20"
                size="20" name="metodologia" id="metodologia" value="{{ disciplina_ofertada.metodologia }}">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-grupo">
                <label for="coordenador">Coordenador:</label>
                <label class="ast">*</label> <br>
                <select name="coordenador">
                    {% for coordenador in coordenadores %}
                        <option value="{{ coordenador.id }}"
                                {% if coordenador.id == disciplina_ofertada.idcoordenador.id %}selected{% endif %}>
                            {{ coordenador.nome }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-grupo">
                <label for="disciplina">Disciplina:</label>
                <label class="ast">*</label> <br>
                <select name="disciplina">
                    {% for disciplina in disciplinas %}
                        <option value="{{ disciplina.id }}"
                                {% if disciplina.id == disciplina_ofertada.iddisciplina.id %}selected{% endif %}>
                            {{ disciplina.nome }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-grupo">
                <label for="datafim">Data Fim:</label>
                <input type="date" size="20"
                size="20" name="datafim" id="datafim" value="{{ datafim }}">
            </div>
            <div class="form-grupo">
                <label for="semestre">Semestre:</label>
                <label class="ast">*</label> <br>
                <input type="number" size="20"
                size="20" name="semestre" id="semestre" value="{{ disciplina_ofertada.semestre }}">
            </div>
            <div class="form-grupo">
                <label for="recursos">Recursos:</label>
                <input type="text" size="20"
                size="20" name="recursos" id="recursos" value="{{ disciplina_ofertada.recursos }}">
            </div>
            <div class="form-grupo">
                <label for="criterio">Critério de Avaliação:</label>
                <input type="text" size="20"
                size="20" name="criterio" id="criterio" value="{{ disciplina_ofertada.criterio_avaliacao }}">
            </div>
        </div>
    </div>
    <div class="linha">
        <div class="col-md-12">
            <div class="form-grupo">
                <label for="planoaulas">Plano de Aulas:</label>
                <textarea rows="10" name="planoaulas">{{ disciplina_ofertada.planode_aulas }}</textarea>
            </div>
        </div>
    </div>
    <div class="form-grupo">
        <button type="submit" class="btn" style="margin-left: 50%;">Salvar Disciplina Ofertada</button>
    </div>
</form>
{% endblock %}

lms/curriculo/templates/cadastro-disciplina.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Cadastro de Disciplinas</h1>
    <hr>

    <form action="{% url 'curriculo:cadastrar-disciplina' %}" method="post">
        <div class="linha">
            {% csrf_token %}
            <input type="number" name="id" hidden value="{{ disciplina.id }}">
            <div class="col-md-6">
                <div class="form-grupo">
                    <label for="nome">Nome:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" size="20"
                    size="20" name="nome" id="nome" required value="{{ disciplina.nome }}">
                </div>
                <div class="form-grupo">
                    <label for="status">Status:</label>
                    <label class="ast">*</label> <br>
                    <select name="status">
                        <option value="Aberta" {% if disciplina.status == 'Aberta' %}selected{% endif %}>Aberta</option>
                        <option value="Fechada" {% if disciplina.status == 'Fechada' %}selected{% endif %}>Fechada</option>
                    </select>
                </div>
                <div class="form-grupo">
                    <label for="pratico">Percentual Prático:</label>
                    <input type="number" size="20"
                    size="20" name="pratico" id="pratico" value="{{ disciplina.percentual_pratico }}">
                </div>
                <div class="form-grupo">
                    <label for="competencias">Competências:</label>
                    <textarea rows="10" name="competencias">{{ disciplina.competencias }}</textarea>
                </div>
                <div class="form-grupo">
                    <label for="basica">Bibliografia Básica:</label>
                    <textarea rows="10" name="basica">{{ disciplina.bibliografia_basica }}</textarea>
                </div>
                <div class="form-grupo">
                    <label for="conteudo">Conteúdo Programatico:</label>
                    <textarea rows="15" name="conteudo">{{ disciplina.conteudo_programatico }}</textarea>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-grupo">
                    <label for="coordenador">Coordenador:</label>
                    <label class="ast">*</label> <br>
                    <select name="coordenador">
                        {% for coordenador in coordenadores %}
                            <option value="{{ coordenador.id }}"
                                    {% if coordenador.id == disciplina.idcoordenador.id %}selected{% endif %}>
                                {{ coordenador.nome }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-grupo">
                    <label for="cargahoraria">Carga Horária:</label>
                    <label class="ast">*</label> <br>
                    <input type="number" size="20"
                    size="20" name="cargahoraria" id="cargahoraria" required value="{{ disciplina.carga_horaria }}">
                </div>
                <div class="form-grupo">
                    <label for="teorico">Percentual Teórico:</label>
                    <input type="number" size="20"
                    size="20" name="teorico" id="teorico" value="{{ disciplina.percentual_teorico }}">
                </div>
                <div class="form-grupo">
                    <label for="habilidades">Habilidades:</label>
                    <textarea rows="10" name="habilidades">{{ disciplina.habilidades }}</textarea>
                </div>
                <div class="form-grupo">
                    <label for="complementar">Bibliografia Complementar:</label>
                    <textarea rows="10" name="complementar">{{ disciplina.bibliografia_complementar }}</textarea>
                </div>
                <div class="form-grupo">
                    <label for="ementa">Ementa:</label>
                    <textarea rows="15" name="ementa">{{ disciplina.ementa }}</textarea>
                </div>
            </div>
        </div>
        <div class="linha">
            <div class="col-md-12">
                <div class="form-grupo">
                    <label for="ensino">Plano de Ensino:</label>
                    <textarea rows="15" name="ensino">{{ disciplina.plano_ensino }}</textarea>
                </div>
            </div>
        </div>
        <div class="form-grupo">
            <button type="submit" class="btn" style="margin-left: 50%;">Salvar Disciplina</button>
        </div>
    </form>
{% endblock %}

lms/curriculo/templates/lista-cursos.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Lista de Cursos</h1>

    <a href="{% url 'curriculo:cadastrar-curso' %}" class="botao">Novo Curso</a>
    <br />
    <table id="cursos" class="alunos">
        <thead>
            <tr>
                <th>Nome</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for curso in cursos %}
                <tr>
                    <td>{{ curso.nome }}</td>
                    <td>
                        <a href="{% url 'curriculo:altera-curso' curso.id %}">Editar</a>
                    </td>
                    <td>
                        <form action="{% url 'curriculo:excluir-curso' curso.id %}" method="post">
                            {% csrf_token %}
                            <a href="#" id="excluir" onclick="excluir({{ curso.id }}, this)">Excluir</a>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">
        function excluir(id, e) {
            var form = e.parentNode;
            if (confirm("Deseja realmente exluir curso?")){
                form.submit()
            }
        }
    </script>
{% endblock %}

lms/curriculo/templates/lista-disciplinas-ofertadas.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Lista de Disciplinas</h1>

    <a href="{% url 'curriculo:cadastrar-disciplina-ofertada' %}" class="botao">Nova Disciplina Ofertada</a>
    <br />
    <table id="disciplinas" class="alunos">
        <thead>
            <tr>
                <th>Professor</th>
                <th>Ano</th>
                <th>Semestre</th>
                <th>Turma</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for disciplina_ofertada in disciplinas_ofertadas %}
                <tr>
                    <td>{{ disciplina_ofertada.idprofessor.nome }}</td>
                    <td>{{ disciplina_ofertada.ano }}</td>
                    <td>{{ disciplina_ofertada.semestre }}</td>
                    <td>{{ disciplina_ofertada.turma }}</td>
                    <td>
                        <a href="{% url 'curriculo:altera-disciplina-ofertada' disciplina_ofertada.id %}">Editar</a>
                    </td>
                    <td>
                        <form action="{% url 'curriculo:excluir-disciplina-ofertada' disciplina_ofertada.id %}" method="post">
                            {% csrf_token %}
                            <a href="#" id="excluir" onclick="excluir({{ disciplina_ofertada.id }}, this)">Excluir</a>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">
        function excluir(id, e) {
            var form = e.parentNode;
            if (confirm("Deseja realmente exluir disciplina ofertada?")){
                form.submit()
            }
        }
    </script>
{% endblock %}

lms/curriculo/templates/lista-disciplinas.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Lista de Disciplinas</h1>

    <a href="{% url 'curriculo:cadastrar-disciplina' %}" class="botao">Nova Disciplina</a>
    <br />
    <table id="disciplina" class="alunos">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Status</th>
                <th>Coordenador</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for disciplina in disciplinas %}
                <tr>
                    <td>{{ disciplina.nome }}</td>
                    <td>{{ disciplina.status }}</td>
                    <td>{{ disciplina.idcoordenador.nome }}</td>
                    <td>
                        <a href="{% url 'curriculo:altera-disciplina' disciplina.id %}">Editar</a>
                    </td>
                    <td>
                        <form action="{% url 'curriculo:excluir-disciplina' disciplina.id %}" method="post">
                            {% csrf_token %}
                            <a href="#" id="excluir" onclick="excluir({{ disciplina.id }}, this)">Excluir</a>
                        </form>
                    </td>
                    <td>
                        <a href="{% url 'curriculo:cadastrar-disciplina-ofertada' %}">Vincular</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">
        function excluir(id, e) {
            var form = e.parentNode;
            if (confirm("Deseja realmente exluir disciplina?")){
                form.submit()
            }
        }
    </script>
{% endblock %}