lms/contas/urls.py
from django.urls import path
from contas import views

app_name = 'contas'

urlpatterns = [
    path('lista-alunos/', views.listar_alunos, name='lista-alunos'),
    path('cadastrar-aluno/', views.cadastrar_alunos, name='cadastrar-aluno'),
    path('altera-aluno/<int:aluno_id>/', views.alterar_aluno, name='altera-aluno'),
    path('excluir-aluno/<int:aluno_id>/', views.excluir_aluno, name='excluir-aluno'),
    path('lista-coordenadores/', views.listar_coordenadores, name='lista-coordenadores'),
    path('cadastrar-coordenador/', views.cadastrar_coordenador, name='cadastrar-coordenador'),
    path('altera-coordenador/<int:coordenador_id>/', views.alterar_coordenador, name='altera-coordenador'),
    path('excluir-coordenador/<int:coordenador_id>/', views.excluir_coordenador, name='excluir-coordenador'),
    path('lista-professores/', views.listar_professores, name='lista-professores'),
    path('cadastrar-professor/', views.cadastrar_professor, name='cadastrar-professor'),
    path('altera-professor/<int:professor_id>/', views.alterar_professor, name='altera-professor'),
    path('excluir-professor/<int:professor_id>/', views.excluir_professor, name='excluir-professor'),
    path('lista-mensagens/', views.listar_mensagens, name='lista-mensagens'),
    path('cadastrar-mensagem/', views.cadastrar_mensagem, name='cadastrar-mensagem'),
    path('altera-mensagem/<int:mensagem_id>/', views.alterar_mensagem, name='altera-mensagem'),
    path('excluir-mensagem/<int:mensagem_id>/', views.excluir_mensagem, name='excluir-mensagem')
]

lms/lms/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

lms/contas/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Aluno(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    login = models.CharField(db_column='LOGIN', unique=True, max_length=15)  # Field name made lowercase.
    senha = models.CharField(db_column='SENHA', max_length=8)  # Field name made lowercase.
    nome = models.CharField(db_column='NOME', max_length=45)  # Field name made lowercase.
    email = models.CharField(db_column='EMAIL', unique=True, max_length=70)  # Field name made lowercase.
    celular = models.CharField(db_column='CELULAR', unique=True, max_length=15)  # Field name made lowercase.
    dtexpiracao = models.DateTimeField(db_column='DTEXPIRACAO', blank=True, null=True)  # Field name made lowercase.
    ra = models.IntegerField(db_column='RA')  # Field name made lowercase.
    foto = models.CharField(db_column='FOTO', max_length=200, blank=True, null=True)  # Field name made lowercase.
    datanascimento = models.DateField()
    cpf = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'aluno'

class Coordenador(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    login = models.CharField(db_column='LOGIN', unique=True, max_length=15)  # Field name made lowercase.
    senha = models.CharField(db_column='SENHA', max_length=8)  # Field name made lowercase.
    nome = models.CharField(db_column='NOME', max_length=45)  # Field name made lowercase.
    email = models.CharField(db_column='EMAIL', unique=True, max_length=70)  # Field name made lowercase.
    celular = models.CharField(db_column='CELULAR', unique=True, max_length=15)  # Field name made lowercase.
    dtexpiracao = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'coordenador'

class Mensagem(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    idaluno = models.ForeignKey(Aluno, models.DO_NOTHING, db_column='IDALUNO')  # Field name made lowercase.
    idprofessor = models.ForeignKey('Professor', models.DO_NOTHING, db_column='IDPROFESSOR')  # Field name made lowercase.
    assunto = models.CharField(db_column='ASSUNTO', max_length=60)  # Field name made lowercase.
    referencia = models.CharField(db_column='REFERENCIA', max_length=40)  # Field name made lowercase.
    conteudo = models.CharField(db_column='CONTEUDO', max_length=200)  # Field name made lowercase.
    status = models.CharField(db_column='STATUS', unique=True, max_length=10)  # Field name made lowercase.
    dtenvio = models.DateTimeField(db_column='DTENVIO')  # Field name made lowercase.
    dtresposta = models.DateField(db_column='DTRESPOSTA', blank=True, null=True)  # Field name made lowercase.
    resposta = models.CharField(db_column='RESPOSTA', max_length=200, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'mensagem'


class Professor(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    login = models.CharField(db_column='LOGIN', unique=True, max_length=15)  # Field name made lowercase.
    senha = models.CharField(db_column='SENHA', max_length=8)  # Field name made lowercase.
    nome = models.CharField(db_column='NOME', max_length=45)  # Field name made lowercase.
    email = models.CharField(db_column='EMAIL', unique=True, max_length=70)  # Field name made lowercase.
    celular = models.CharField(db_column='CELULAR', unique=True, max_length=15)  # Field name made lowercase.
    dtexpiracao = models.DateField(db_column='DTEXPIRACAO')  # Field name made lowercase.
    apelido = models.CharField(db_column='APELIDO', max_length=20)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'professor'

lms/contas/views.py
from django.shortcuts import render

# Create your views here.

lms/contas/templates/cadastro-aluno.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <h1 class="text-center">Cadastro de Alunos</h1>
    <hr>

    <form action="{% url 'contas:cadastrar-aluno' %}" method="post" id="cadastro-aluno">
        <div class="linha">
            {% csrf_token %}
            <input type="number" name="id" hidden value="{{ aluno.id }}">
            <div class="col-md-6">
                <div class="form-grupo">
                    <label for="ra">RA:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" size="20 "maxlength="20"
                    size="20" name="ra" id="ra" required value="{{ aluno.ra }}">
                </div>
                <div class="form-grupo">
                    <label for="login">Login:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" size="20 "maxlength="20"
                    size="20" name="login" id="login" required value="{{ aluno.login }}">
                </div>
                <div class="form-grupo">
                    <label for="nome">Nome:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" maxlength="45"
                    size="45" name="nome" id="nome" required value="{{ aluno.nome }}">
                </div>
                <div class="form-grupo">
                    <label for="email">E-mail:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" maxlength="70"
                    size="70" name="email" id="email" required value="{{ aluno.email }}">
                </div>
                <div class="form-grupo">
                    <label for="celular">Celular:</label> <br>
                    <input type="text" maxlength="15"
                    size="15" name="celular" id="celular" value="{{ aluno.celular }}">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-grupo">
                    <label for="nascimento">Nascimento:</label>
                    <label class="ast">*</label> <br>
                    <input type="date" id="nascimento" name="nascimento" required value="{{ nascimento }}">
                </div>
                <div class="form-grupo">
                    <label for="cpf">CPF:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" maxlength="13" size="13" required id="cpf" name="cpf" value="{{ aluno.cpf }}">
                </div>
                <div class="form-grupo">
                    <label for="senha">Senha:</label>
                    <label class="ast">*</label> <br>
                    <input type="password" maxlength="8" size="8" name="senha" required
                    id="senha" value="{{ aluno.senha }}">
                </div>
                <div class="form-grupo">
                    <label for="confirmSenha">Confirmar Senha:</label>
                    <label class="ast">*</label> <br>
                    <input type="password" maxlength="8"
                    size="8" name="confirmSenha" required
                    id="confirmSenha" value="{{ aluno.senha }}">
                </div>
                <p class="ast">* informações obrigatórias</p>
            </div>
            <br>
            <br>
            <div class="form-grupo">
                <button type="submit" class="btn" style="margin-left: 50%;">Salvar Aluno</button>
            </div>
        </div>
    </form>
    <script src="{% static 'js/alunos.js' %}"></script>
{% endblock %}

lms/contas/templates/cadastro-coordenador.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Cadastro de Coordenadores</h1>
    <hr>
    <form action="{% url 'contas:cadastrar-coordenador' %}" method="post">
        <div class="linha">
            {% csrf_token %}
            <input type="number" name="id" hidden value="{{ coordenador.id }}">
            <div class="col-md-6">
                <div class="form-grupo">
                    <label for="login">Login:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" size="20 "maxlength="20"
                    size="20" name="login" id="login" required value="{{ coordenador.login }}">
                </div>
                <div class="form-grupo">
                    <label for="nome">Nome:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" maxlength="45"
                    size="45" name="nome" id="nome" required value="{{ coordenador.nome }}">
                </div>
                <div class="form-grupo">
                    <label for="email">E-mail:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" maxlength="70"
                    size="70" name="email" id="email" required value="{{ coordenador.email }}">
                </div>
                <div class="form-grupo">
                    <label for="celular">Celular:</label> <br>
                    <input type="text" maxlength="15"
                    size="15" name="celular" id="celular" value="{{ coordenador.celular }}">
                </div>
                <div class="form-grupo">
                    <label for="senha">Senha:</label>
                    <label class="ast">*</label> <br>
                    <input type="password" maxlength="8" size="8" name="senha" required
                    id="senha" value="{{ coordenador.senha }}">
                </div>
                <div class="form-grupo">
                    <label for="confirmSenha">Confirmar Senha:</label>
                    <label class="ast">*</label> <br>
                    <input type="password" maxlength="8"
                    size="8" name="confirmSenha" required
                    id="confirmSenha" value="{{ coordenador.senha }}">
                </div>
                <p class="ast">* informações obrigatórias</p>
                <div class="form-grupo">
                    <button type="submit" class="btn" style="margin-left: 50%;">Salvar Coordenador</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

lms/contas/templates/cadastro-mensagem.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Enviar Mensagem</h1>
    <hr>
    <form action="{% url 'contas:cadastrar-mensagem' %}" method="post">
        <div class="linha">
            {% csrf_token %}
            <input type="number" name="id" hidden value="{{ mensagem.id }}">
            <input type="text" name="envio" hidden value="{{ envio }}">
            <div class="col-md-6">
                <div class="form-grupo">
                    <label for="assunto">Assunto:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" size="20 "maxlength="20"
                    size="20" name="assunto" id="assunto" required value="{{ mensagem.assunto }}">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-grupo">
                    <label for="referencia">Referência:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" size="20 "maxlength="20"
                    size="20" name="referencia" id="referencia" required value="{{ mensagem.referencia }}">
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-grupo">
                    <label for="conteudo">Contéudo:</label>
                    <label class="ast">*</label> <br>
                    <textarea type="text" rows="15"
                         name="conteudo" id="conteudo" required>
                        {{ mensagem.conteudo }}
                    </textarea>
                </div>
            </div>
            <br>
            <div class="form-grupo">
                    <button type="submit" class="btn" style="margin-left: 50%;">Salvar Mensagem</button>
            </div>
        </div>
    </form>
{% endblock %}

lms/contas/templates/cadastro-professor.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Cadastro de Professores</h1>
    <hr>
    <form action="{% url 'contas:cadastrar-professor' %}" method="post">
        <div class="linha">
            {% csrf_token %}
            <input type="number" name="id" hidden value="{{ professor.id }}">
            <div class="col-md-6">
                <div class="form-grupo">
                    <label for="login">Login:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" size="20 "maxlength="20"
                    size="20" name="login" id="login" required value="{{ professor.login }}">
                </div>
                <div class="form-grupo">
                    <label for="nome">Nome:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" maxlength="45"
                    size="45" name="nome" id="nome" required value="{{ professor.nome }}">
                </div>
                <div class="form-grupo">
                    <label for="apelido">Apelido:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" maxlength="45"
                    size="45" name="apelido" id="apelido" required value="{{ professor.apelido }}">
                </div>
                <div class="form-grupo">
                    <label for="email">E-mail:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" maxlength="70"
                    size="70" name="email" id="email" required value="{{ professor.email }}">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-grupo">
                    <label for="celular">Celular:</label> <br>
                    <input type="text" maxlength="15"
                    size="15" name="celular" id="celular" value="{{ professor.celular }}">
                </div>
                <div class="form-grupo">
                    <label for="senha">Senha:</label>
                    <label class="ast">*</label> <br>
                    <input type="password" maxlength="8" size="8" name="senha" required
                    id="senha" value="{{ professor.senha }}">
                </div>
                <div class="form-grupo">
                    <label for="confirmSenha">Confirmar Senha:</label>
                    <label class="ast">*</label> <br>
                    <input type="password" maxlength="8"
                    size="8" name="confirmSenha" required
                    id="confirmSenha" value="{{ professor.senha }}">
                </div>
                <p class="ast">* informações obrigatórias</p>
            </div>
            <div class="form-grupo">
                <button type="submit" class="btn" style="margin-left: 50%;">Salvar Professor</button>
            </div>
        </div>
    </form>
{% endblock %}

lms/contas/templates/lista-alunos.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Lista de Alunos</h1>

    <a href="{% url 'contas:cadastrar-aluno' %}" class="botao">Novo Aluno</a>
    <br />
    <table id="alunos" class="alunos">
        <thead>
            <tr>
                <th>RA</th>
                <th>Nome</th>
                <th>Login</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for aluno in alunos %}
                <tr>
                    <td>{{ aluno.ra }}</td>
                    <td>{{ aluno.nome }}</td>
                    <td>{{ aluno.login }}</td>
                    <td>
                        <a href="{% url 'contas:altera-aluno' aluno.id %}">Editar</a>
                    </td>
                    <td>
                        <form action="{% url 'contas:excluir-aluno' aluno.id %}" method="post">
                            {% csrf_token %}
                            <a href="#" id="excluir" onclick="excluir({{ aluno.id }}, this)">Excluir</a>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">
        function excluir(id, e) {
            var form = e.parentNode;
            if (confirm("Deseja realmente exluir aluno?")){
                form.submit()
            }
        }
    </script>
{% endblock %}

lms/contas/templates/lista-coordenadores.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Lista de Coordenadores</h1>

    <a href="{% url 'contas:cadastrar-coordenador' %}" class="botao">Novo Coordenador</a>
    <br />
    <table id="coordenadores" class="alunos">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Login</th>
                <th>Email</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for coordenador in coordenadores %}
                <tr>
                    <td>{{ coordenador.nome }}</td>
                    <td>{{ coordenador.login }}</td>
                    <td>{{ coordenador.email }}</td>
                    <td>
                        <a href="{% url 'contas:altera-coordenador' coordenador.id %}">Editar</a>
                    </td>
                    <td>
                        <form action="{% url 'contas:excluir-coordenador' coordenador.id %}" method="post">
                            {% csrf_token %}
                            <a href="#" id="excluir" onclick="excluir({{ coordenador.id }}, this)">Excluir</a>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">
        function excluir(id, e) {
            var form = e.parentNode;
            if (confirm("Deseja realmente exluir coordenador?")){
                form.submit()
            }
        }
    </script>
{% endblock %}

lms/contas/templates/lista-mensagens.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Lista de Mensagens</h1>

    <a href="{% url 'contas:cadastrar-mensagem' %}" class="botao">Nova Mensagem</a>
    <br />
    <table id="mensagens" class="alunos">
        <thead>
            <tr>
                <th>Assunto</th>
                <th>Referência</th>
                <th>Status</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for mensagem in mensagens %}
                <tr>
                    <td>{{ mensagem.assunto }}</td>
                    <td>{{ mensagem.referencia }}</td>
                    <td>{{ mensagem.status }}</td>
                    <td>
                        <a href="{% url 'contas:altera-mensagem' mensagem.id %}">Editar</a>
                    </td>
                    <td>
                        <form action="{% url 'contas:excluir-mensagem' mensagem.id %}" method="post">
                            {% csrf_token %}
                            <a href="#" id="excluir" onclick="excluir({{ mensagem.id }}, this)">Excluir</a>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">
        function excluir(id, e) {
            var form = e.parentNode;
            if (confirm("Deseja realmente exluir professor?")){
                form.submit()
            }
        }
    </script>
{% endblock %}

lms/contas/templates/lista-professores.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Lista de Professores</h1>

    <a href="{% url 'contas:cadastrar-professor' %}" class="botao">Novo Professor</a>
    <br />
    <table id="alunos" class="alunos">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Login</th>
                <th>Email</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for professor in professores %}
                <tr>
                    <td>{{ professor.nome }}</td>
                    <td>{{ professor.login }}</td>
                    <td>{{ professor.email }}</td>
                    <td>
                        <a href="{% url 'contas:altera-professor' professor.id %}">Editar</a>
                    </td>
                    <td>
                        <form action="{% url 'contas:excluir-professor' professor.id %}" method="post">
                            {% csrf_token %}
                            <a href="#" id="excluir" onclick="excluir({{ professor.id }}, this)">Excluir</a>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">
        function excluir(id, e) {
            var form = e.parentNode;
            if (confirm("Deseja realmente exluir professor?")){
                form.submit()
            }
        }
    </script>
{% endblock %}