lms/contas/urls.py
from django.urls import path
from contas import views

app_name = 'contas'

urlpatterns = [
    path('lista-alunos/', views.listar_alunos, name='lista-alunos'),
    path('cadastrar-aluno/', views.cadastrar_alunos, name='cadastrar-aluno'),
    path('altera-aluno/<int:aluno_id>/', views.alterar_aluno, name='altera-aluno'),
    path('excluir-aluno/<int:aluno_id>/', views.excluir_aluno, name='excluir-aluno'),
    path('lista-coordenadores/', views.listar_coordenadores, name='lista-coordenadores'),
    path('cadastrar-coordenador/', views.cadastrar_coordenador, name='cadastrar-coordenador'),
    path('altera-coordenador/<int:coordenador_id>/', views.alterar_coordenador, name='altera-coordenador'),
    path('excluir-coordenador/<int:coordenador_id>/', views.excluir_coordenador, name='excluir-coordenador'),
    path('lista-professores/', views.listar_professores, name='lista-professores'),
    path('cadastrar-professor/', views.cadastrar_professor, name='cadastrar-professor'),
    path('altera-professor/<int:professor_id>/', views.alterar_professor, name='altera-professor'),
    path('excluir-professor/<int:professor_id>/', views.excluir_professor, name='excluir-professor'),
    path('lista-mensagens/', views.listar_mensagens, name='lista-mensagens'),
    path('cadastrar-mensagem/', views.cadastrar_mensagem, name='cadastrar-mensagem'),
    path('altera-mensagem/<int:mensagem_id>/', views.alterar_mensagem, name='altera-mensagem'),
    path('excluir-mensagem/<int:mensagem_id>/', views.excluir_mensagem, name='excluir-mensagem')
]

lms/core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index')
]

lms/curriculo/urls.py
from django.urls import path
from curriculo import views

app_name = 'curriculo'

urlpatterns = [
    path('lista-cursos/', views.listar_cursos, name='lista-cursos'),
    path('cadastrar-curso/', views.cadastrar_curso, name='cadastrar-curso'),
    path('altera-curso/<int:curso_id>/', views.alterar_curso, name='altera-curso'),
    path('excluir-curso/<int:curso_id>/', views.excluir_curso, name='excluir-curso'),

    path('lista-disciplinas/', views.listar_disciplinas, name='lista-disciplinas'),
    path('cadastrar-disciplina/', views.cadastrar_disciplina, name='cadastrar-disciplina'),
    path('altera-disciplina/<int:disciplina_id>/', views.alterar_disciplina, name='altera-disciplina'),
    path('excluir-disciplina/<int:disciplina_id>/', views.excluir_disciplina, name='excluir-disciplina'),

    path('lista-disciplinas-ofertadas/', views.listar_disciplinas_ofertadas, name='lista-disciplinas-ofertadas'),
    path('cadastrar-disciplina-ofertada/', views.cadastrar_disciplina_ofertada, name='cadastrar-disciplina-ofertada'),
    path('altera-disciplina-ofertada/<int:id>/', views.alterar_disciplina_ofertada, name='altera-disciplina-ofertada'),
    path('excluir-disciplina-ofertada/<int:id>/', views.excluir_disciplina_ofertada, name='excluir-disciplina-ofertada')
]

lms/lms/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

lms/restrito/urls.py
from django.urls import path
from restrito import views

app_name = 'restrito'

urlpatterns = [
    path('lista-atividades', views.listar_atividades, name='lista-atividades'),
    path('cadastrar-atividade', views.cadastrar_atividade, name='cadastrar-atividade'),
    path('alterar-atividade/<int:atividade_id>', views.alterar_atividade, name='alterar-atividade'),
    path('excluir-atividade/<int:atividade_id>', views.excluir_atividade, name='excluir-atividade')
]

lms/restrito/models.py
from django.db import models

# Create your models here.
class Solicitacaomatricula(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    idaluno = models.ForeignKey(Aluno, models.DO_NOTHING, db_column='IDALUNO')  # Field name made lowercase.
    iddisciplinaofertada = models.ForeignKey(Disciplinaofertada, models.DO_NOTHING, db_column='IDDISCIPLINAOFERTADA')  # Field name made lowercase.
    dtsolicitacao = models.DateTimeField(db_column='DTSOLICITACAO')  # Field name made lowercase.
    idcoordenador = models.ForeignKey(Coordenador, models.DO_NOTHING, db_column='IDCOORDENADOR', blank=True, null=True)  # Field name made lowercase.
    status = models.CharField(db_column='STATUS', max_length=10, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'solicitacaomatricula'

class Atividade(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    titulo = models.CharField(db_column='TITULO', unique=True, max_length=30)  # Field name made lowercase.
    descricao = models.CharField(db_column='DESCRICAO', max_length=60, blank=True, null=True)  # Field name made lowercase.
    conteudo = models.CharField(db_column='CONTEUDO', max_length=200, blank=True, null=True)  # Field name made lowercase.
    tipo = models.CharField(db_column='TIPO', max_length=18, blank=True, null=True)  # Field name made lowercase.
    extras = models.CharField(db_column='EXTRAS', max_length=180, blank=True, null=True)  # Field name made lowercase.
    idprofessor = models.ForeignKey('Professor', models.DO_NOTHING, db_column='IDPROFESSOR')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'atividade'

class Atividadevinculada(models.Model):
    id = models.ForeignKey(Atividade, models.DO_NOTHING, db_column='ID', primary_key=True)  # Field name made lowercase.
    idatividade = models.IntegerField(db_column='IDATIVIDADE')  # Field name made lowercase.
    idprofessor = models.ForeignKey('Professor', models.DO_NOTHING, db_column='IDPROFESSOR')  # Field name made lowercase.
    iddisciplinaofertada = models.ForeignKey('Disciplinaofertada', models.DO_NOTHING, db_column='IDDISCIPLINAOFERTADA')  # Field name made lowercase.
    rotulo = models.CharField(db_column='ROTULO', max_length=5)  # Field name made lowercase.
    status = models.CharField(db_column='STATUS', max_length=20)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'atividadevinculada'
        unique_together = (('idatividade', 'iddisciplinaofertada', 'rotulo'),)

class Entrega(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    idaluno = models.ForeignKey(Aluno, models.DO_NOTHING, db_column='IDALUNO', unique=True)  # Field name made lowercase.
    idatividadevinculada = models.ForeignKey(Atividadevinculada, models.DO_NOTHING, db_column='IDATIVIDADEVINCULADA')  # Field name made lowercase.
    titulo = models.CharField(db_column='TITULO', max_length=30)  # Field name made lowercase.
    resposta = models.CharField(db_column='RESPOSTA', max_length=200)  # Field name made lowercase.
    dtentrega = models.DateTimeField(db_column='DTENTREGA')  # Field name made lowercase.
    status = models.CharField(db_column='STATUS', max_length=15)  # Field name made lowercase.
    idprofessor = models.IntegerField(db_column='IDPROFESSOR', blank=True, null=True)  # Field name made lowercase.
    nota = models.SmallIntegerField(db_column='NOTA', blank=True, null=True)  # Field name made lowercase.
    dtavaliacao = models.DateField(db_column='DTAVALIACAO', blank=True, null=True)  # Field name made lowercase.
    obs = models.CharField(db_column='OBS', max_length=90, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'entrega'

lms/restrito/views.py
from django.shortcuts import render

# Create your views here.

lms/restrito/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static "css/normalize.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>LMS - Home</title>
</head>
<body>

    <nav>
        <ul class="menu">
            <li>&nbsp;&nbsp;&nbsp;</li>
            <li><a href="{% url 'core:index' %}">LMS</a></li>
            <li><a href="{% url 'contas:lista-alunos' %}">Aluno</a></li>
            <li><a href="{% url 'contas:lista-coordenadores' %}">Coordenador</a></li>
            <li><a href="{% url 'contas:lista-professores' %}">Professor</a></li>
            <li><a href="{% url 'contas:lista-mensagens' %}">Mensagem</a></li>
            <li><a href="{% url 'curriculo:lista-cursos' %}">Curso</a></li>
            <li><a href="{% url 'curriculo:lista-disciplinas' %}">Disciplina</a></li>
            <li><a href="{% url 'restrito:lista-atividades' %}">Atividades</a></li>
            <li class="right"><a href="login.html" target="_blank">Login</a></li>
            <li class="right">&nbsp;</li>
        </ul>
    </nav>

    <div class="conteudo">
        {% block body %}
        {% endblock %}
    </div>

    <footer>
        <div>
            <div class="linha">
                <div class="col-md-4">
                    <h1>LMS</h1>
                    <p class="sociais">Siga a gente nas redes sociais</p>
                    <img src="{% static 'img/facebook.png' %}" alt="Facebook">
                    <img src="{% static 'img/twitter.png' %}" alt="Twitter">
                    <img src="{% static 'img/linkedin.png' %}" alt="Linkedin">
                    <img src="{% static 'img/instagram.png' %}" alt="Instagram">
                    <p>Todos os direitos reservados.</p>
                </div>
                <div class="col-md-4">
                    <h2>Contato</h2>
                    <p><strong>Telefone</strong></p>
                    <p>(11) 4141-4141</p>
                    <p><strong>Endereço</strong></p>
                    <p>Rua X, 44 - Bairro Y - Cidade Z / SP </p>
                </div>
                <div class="col-md-4">
                    <h2>Atendimento</h2>
                    <p>De Segunda a Sexta - Das 8h ás 22h</p>
                </div>

            </div>
        </div>
    </footer>
<script src="{% static 'js/alunos.js' %}"></script>
</body>
</html>

lms/restrito/templates/cadastro-atividade.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Cadastro de Atividades</h1>
    <hr>

    <form action="{% url 'restrito:cadastrar-atividade' %}" method="post">
        <div class="linha">
            {% csrf_token %}
            <input type="number" name="id" hidden value="{{ atividade.id }}">
            <div class="col-md-6">
                <div class="form-grupo">
                    <label for="titulo">Titulo:</label>
                    <label class="ast">*</label> <br>
                    <input type="text" size="20"
                    size="20" name="titulo" id="titulo" required value="{{ atividade.titulo }}">
                </div>
                <div class="form-grupo">
                    <label for="tipo">Tipo:</label>
                    <label class="ast">*</label> <br>
                    <select name="tipo">
                        <option value="Resposta Aberta" {% if atividade.tipo == 'Resposta Aberta' %}selected{% endif %}>
                            Resposta Aberta</option>
                        <option value="Teste" {% if atividade.tipo == 'Teste' %}selected{% endif %}>Teste</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-grupo">
                    <label for="descricao">Descrição:</label>
                    <input type="text" size="20"
                    size="20" name="descricao" id="descricao" value="{{ atividade.descricao }}">
                </div>
                <div class="form-grupo">
                    <label for="extras">Extras:</label>
                    <input type="text" size="20"
                    size="20" name="extras" id="extras" value="{{ atividade.extras }}">
                </div>
            </div>
        </div>
        <div class="linha">
            <div class="col-md-12">
                <div class="form-grupo">
                    <label for="conteudo">Conteúdo:</label>
                    <textarea name="conteudo" rows="10">
                        {{ atividade.conteudo }}
                    </textarea>
                </div>
            </div>
        </div>
        <div class="form-grupo">
            <button type="submit" class="btn" style="margin-left: 50%;">Salvar Atividade</button>
        </div>
    </form>
{% endblock %}

lms/restrito/templates/lista-atividades.html
{% extends 'base.html' %}
{% block body %}
    <h1 class="text-center">Lista de Disciplinas</h1>

    <a href="{% url 'restrito:cadastrar-atividade' %}" class="botao">Nova Atividade</a>
    <br />
    <table id="disciplina" class="alunos">
        <thead>
            <tr>
                <th>Título</th>
                <th>Descrição</th>
                <th>Professor</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for atividade in atividades %}
                <tr>
                    <td>{{ atividade.titulo }}</td>
                    <td>{{ atividade.descricao }}</td>
                    <td>{{ atividade.idprofessor.nome }}</td>
                    <td>
                        <a href="{% url 'restrito:alterar-atividade' atividade.id %}">Editar</a>
                    </td>
                    <td>
                        <form action="{% url 'restrito:excluir-atividade' atividade.id %}" method="post">
                            {% csrf_token %}
                            <a href="#" id="excluir" onclick="excluir({{ atividade.id }}, this)">Excluir</a>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">
        function excluir(id, e) {
            var form = e.parentNode;
            if (confirm("Deseja realmente exluir atividade?")){
                form.submit()
            }
        }
    </script>
{% endblock %}